stages:
  - docker

realizar_testes:
  stage: docker
  image: node:20.7.0-alpine3.17
  before_script:
    - cd app/
    - npm install
  script:
    - npm docker

  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

build_docker_image:
  stage: build
  needs: 
    - realizar_testes
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind

    variables:
      DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy_dev:
  stage: deploy
  needs: 
    - build_docker_image
  image: alpine:3.14
  script:
    - docker run -d --name app -p 3000:3000 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA