name: CI/CD Pipeline

on:
  push:
    branches:
      - kubernetes

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine3.14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      
      - name: Install dependencies
        run: |
          cd app/
          npm install
      
      - name: Run tests
        run: npm test
      
      - name: Store test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/junit.xml

  build:
    runs-on: ubuntu-latest
    needs: test
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build Docker image
        run: docker build -t warrp/gitlab-cicd-node:1.0 .

      - name: Push Docker image
        run: docker push warrp/gitlab-cicd-node:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@35.198.57.187 << 'EOF'
            sudo rm -Rf *
            sudo git clone --branch kubernetes https://Raphaellaucene/github-cicd-app-base.git
            cd github-cicd-app-base
            kubectl apply -f deployment.yml
          EOF
